package Vista;

import Controlador.Controller;
import Modelo.EntidadEmpleado;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ebarrero
 */
public class Login extends javax.swing.JFrame {
    
    Controller llamar=null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       llamar= new Controller();
//        this.textoErrorUser.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jpIngreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        textoPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btnlogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textoErrorPass = new javax.swing.JLabel();
        textoErrorUser = new javax.swing.JLabel();
        textoErrorSesion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(766, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(238, 112, 82));
        jLabel2.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("PASSWORD: ");
        jpIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, 30));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("USER: ");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_User_96px_2.png"))); // NOI18N
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 80));

        textoUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textoUser.setBorder(null);
        textoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUserActionPerformed(evt);
            }
        });
        jpIngreso.add(textoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, 30));
        jpIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 180, 10));
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 10));

        textoPassword.setBorder(null);
        jpIngreso.add(textoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_customer_32px_1.png"))); // NOI18N
        jpIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 40, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Key_32px.png"))); // NOI18N
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 40, 30));

        Btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Enter_OFF.png"))); // NOI18N
        Btnlogin.setBorder(null);
        Btnlogin.setBorderPainted(false);
        Btnlogin.setContentAreaFilled(false);
        Btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btnlogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Enter_ON.png"))); // NOI18N
        Btnlogin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Enter_ON.png"))); // NOI18N
        Btnlogin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Enter_ON.png"))); // NOI18N
        Btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnloginActionPerformed(evt);
            }
        });
        jpIngreso.add(Btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 40));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 112, 82));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("INICIAR SESION");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 210, 30));

        jpIngreso.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 50));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpIngreso.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 290, 50));

        textoErrorPass.setForeground(new java.awt.Color(255, 0, 51));
        textoErrorPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpIngreso.add(textoErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 180, 20));

        textoErrorUser.setForeground(new java.awt.Color(255, 0, 51));
        textoErrorUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpIngreso.add(textoErrorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 20));

        textoErrorSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpIngreso.add(textoErrorSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 240, 20));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 480));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AUTOR - ALVARO");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 220, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 470, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 540, 530));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Multiply_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 50));

        jLabel11.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MUDIR SYSTEM");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 470, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUserActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       int dialog=JOptionPane.YES_NO_OPTION;
       int result=JOptionPane.showConfirmDialog(null,"Desea salir?","Exit",dialog);
       if (result==0) 
       {
          System.exit(0); 
       }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void BtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnloginActionPerformed
        
        
        String usu=textoUser.getText().trim();
        textoErrorSesion.setText("");
        if (llamar.validarCampoVacios(usu)) 
        {
            textoErrorUser.setText("");
            String pass=textoPassword.getText().trim();
            if (llamar.validarCampoVacios(pass) ) 
            {
                textoErrorPass.setText("");
                if (llamar.validarDatosSesion(usu, pass)) 
                {
                    textoErrorSesion.setText("");
                    textoUser.setText("");
                    textoPassword.setText("");

                    EntidadEmpleado myUsu=(EntidadEmpleado) llamar.consultarEmpleado(usu);
                    
                    menu menuPrincipal= new menu();
                    menuPrincipal.setVisible(true);
                    menuPrincipal.setLocationRelativeTo(null);
                    this.dispose();
                }else{
                    textoErrorSesion.setForeground(Color.red);
                    textoErrorSesion.setText("USAURIO O PASSWORD INCORRECTOS");
                    textoUser.setText("");
                    textoPassword.setText("");
                }
            }else{
                textoErrorPass.setForeground(Color.red);
                textoErrorPass.setText("CAMPO OBLIGATORIO");
                textoPassword.setText("");
            }  
        }else{
            textoErrorUser.setForeground(Color.red);
            textoErrorUser.setText("CAMPO OBLIGATORIO");
            textoUser.setText(""); 
        }
 
    }//GEN-LAST:event_BtnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JLabel textoErrorPass;
    private javax.swing.JLabel textoErrorSesion;
    private javax.swing.JLabel textoErrorUser;
    public javax.swing.JPasswordField textoPassword;
    public javax.swing.JTextField textoUser;
    // End of variables declaration//GEN-END:variables
}
